### ISSUE TITLE
How to detokenize a BertTokenizer output?

### ISSUE THREAD

**Issue by bprabhakar** [huggingface/pytorch-pretrained-BERT#36]
I was wondering if there's a proper way of detokenizing the output tokens, i.e., constructing the sentence back from the tokens? Considering the fact that the word-piece tokenisation introduces lots of `#`s.

**Comment by artemisart** [comment]
You can remove ' ##' but you cannot know it there was a space around punctuations tokens or uppercase words.

**Comment by thomwolf** [comment]
Yes. I don't plan to include a reverse conversion of tokens in the tokenizer.
For an example on how to keep track of the original characters position, please read the `run_squad.py` example.

**Comment by littlethunder** [comment]
In my case, I do: 
`tokens = ['[UNK]', '[CLS]', '[SEP]', 'want', '##ed', 'wa', 'un', 'runn', '##ing', ',']
text = ' '.join([x for x in tokens])
fine_text = text.replace(' ##', '')
`

**Comment by robertmash2** [comment]
An imperfect, but reasonable solution:
`answer_text = ''
        for i, token in enumerate(answer_token_list):
            token = token.replace('#', '')
            if token != '':
                answer_text += token
                # if the next char is not a #, then add a space
                if i < len(answer_token_list) - 1 and answer_token_list[i + 1][0] != '#':
                    answer_text += ' '`

**Comment by robertmash2** [comment]
This isn't perfect, but does ok:

answer_text = ''
        for i, token in enumerate(answer_token_list):
            token = token.replace('#', '')
            if token != '':
                answer_text += token
                # if the next char is not a #, then add a space
                if i < len(answer_token_list) - 1 and answer_token_list[i + 1][0] != '#':
                    answer_text += ' '

**Comment by igrinis** [comment]
Apostrophe is considered as a punctuation mark, but often it is an integrated part of the word.  Regular `.tokenize()` always converts apostrophe to the stand alone token, so the information to which word it belongs is lost. If the original sentence contains apostrophes, it is impossible to recreate the original sentence (for example when apostrophe is a last symbol in some word `convert_tokens_to_string()` will join it with the following one). In order to overcome this, one can check the surroundings of the apostrophe and add `##` immediately after the tokenization.  For example:
```
sent = "The Smiths' used their son's car" 
tokens = tokenizer.tokenize(sent)
```
now if you fix `tokens` to look like:

**original** `=>['the', 'smith', '##s', "'",     'used', 'their', 'son', "'",     's',      'car']`
**fixed** `  => ['the', 'smith', '##s', "##'", 'used', 'their', 'son', "##'", '##s', 'car']`

you will be able to restore the original words.

**Comment by pertschuk** [comment]
@thomwolf could you point to the specific section of `run_squad.py` that handles this, I'm having trouble
