### ISSUE TITLE
How can I generate new text after having fine-tuned BERT on a custom dataset ? 

### ISSUE THREAD

**Issue by MoMe36** [huggingface/pytorch-pretrained-BERT#401]
Hey, 

Once I've fine-tuned the Language Model, how can I get it to generate new text ? Is there any example available ? 
Thanks !

**Comment by Astraithious** [comment]
Also interested in this!

**Comment by thomwolf** [comment]
Hi,
It's quite difficult to use BERT to generate text as BERT is not a causal language model per se.
Here is an example: https://github.com/nyu-dl/bert-gen by @W4ngatang and @kyunghyuncho.

**Comment by mhattingpete** [comment]
Bert was not trained for text generation since it's not trained in the classical lm setting. However there are some new approaches that doesn't rely on next word predictions in the classical lm way. Have a look at: [Insertion Transformer](https://arxiv.org/abs/1902.03249) and [Insertion-based Decoding](https://arxiv.org/abs/1902.01370).
